import React,{useEffect,useMemo,useState} from 'react';
import {Routes,Route,Link,useNavigate,useLocation,Navigate} from 'react-router-dom';
import {Camera,ChevronRight,Clock3,Heart,LogIn,Menu,Search,ShieldCheck,Sparkles,Trophy,Upload,Users,BarChart3,LayoutDashboard,Image as ImageIcon,Tag,LogOut,X,CheckCircle2,ArrowUpRight,Filter} from 'lucide-react';
import {api,setSession,getUser,logout} from './api';

const demoPhotos=[
 {id:'d1',title:'Campus Light',category_name:'Campus Life',image_url:'/photos/campus.svg',vote_count:128,student_name:'Aarav S.'},
 {id:'d2',title:'After Rain',category_name:'Nature & Landscape',image_url:'/photos/nature.svg',vote_count:112,student_name:'Riya M.'},
 {id:'d3',title:'Quiet Portrait',category_name:'Portraits',image_url:'/photos/portrait.svg',vote_count:97,student_name:'Ananya D.'},
 {id:'d4',title:'Lines & Light',category_name:'Architecture',image_url:'/photos/architecture.svg',vote_count:88,student_name:'Rahul K.'},
 {id:'d5',title:'Pocket Stories',category_name:'Mobile Photography',image_url:'/photos/mobile.svg',vote_count:79,student_name:'Ishita P.'},
 {id:'d6',title:'Unexpected',category_name:'Open Category',image_url:'/photos/open.svg',vote_count:71,student_name:'Kabir N.'}
];

function useData(){
 const [competition,setCompetition]=useState(null); const [categories,setCategories]=useState([]); const [photos,setPhotos]=useState([]); const [loading,setLoading]=useState(true);
 const refresh=async()=>{setLoading(true);try{const [c,cs,p]=await Promise.all([api('/competition'),api('/categories'),api('/photos')]);setCompetition(c);setCategories(cs);setPhotos(p.length?p:demoPhotos);}catch{setCompetition({title:'IEM Photography Competition 2026',theme:'Through Your Lens',status:'live',ends_at:'2026-10-31T18:30:00.000Z'});setCategories(['Campus Life','Nature & Landscape','Portraits','Architecture','Mobile Photography','Open Category'].map((name,i)=>({id:i+1,name})));setPhotos(demoPhotos);}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]); return {competition,categories,photos,loading,refresh};
}

function Layout({children}){const u=getUser();const nav=useNavigate();const loc=useLocation();const [open,setOpen]=useState(false);return <div className="app-shell"><header className="topbar"><Link to="/" className="brand"><img src="/iem-logo.jpg"/><span>IEM <b>PHOTO</b></span></Link><button className="menu-btn" onClick={()=>setOpen(!open)}><Menu/></button><nav className={open?'nav open':'nav'}><Link className={loc.pathname==='/'?'active':''} to="/">Home</Link><Link className={loc.pathname==='/gallery'?'active':''} to="/gallery">Explore</Link><Link to="/leaderboard">Leaderboard</Link>{u?.role==='student'&&<Link to="/my-submissions">My Entries</Link>}{u?.role==='organizer'&&<Link to="/organizer">Organizer</Link>}<span className="nav-spacer"/>{u?<button className="ghost-btn" onClick={()=>{logout();nav('/')}}><LogOut size={16}/> Sign out</button>:<><Link to="/login" className="ghost-btn"><LogIn size={16}/> Student Login</Link><Link to="/organizer/login" className="solid-btn">Organizer</Link></>}</nav></header>{children}<footer><div><b>IEM Photography Competition</b><span>Capture • Express • Inspire</span></div><span>Built for IEM / UEM students · 2026</span></footer></div>}

function Home(){const {competition,photos}=useData();const [days,setDays]=useState('--');useEffect(()=>{const tick=()=>{const end=new Date(competition?.ends_at||'2026-10-31T18:30:00+05:30').getTime();setDays(Math.max(0,Math.ceil((end-Date.now())/86400000)))};tick();const t=setInterval(tick,60000);return()=>clearInterval(t)},[competition]);return <main>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> IEM / UEM · ANNUAL VISUAL STORIES</div><h1>See the<br/><em>ordinary</em><br/>differently.</h1><p>The organizers curate and publish the photographs. Explore every category, discover the stories, and cast your vote for the frames that deserve to win.</p><div className="hero-actions"><Link to="/gallery" className="solid-btn big">Explore the gallery <ArrowUpRight size={18}/></Link><Link to={getUser()?.role==='student'?'/gallery':'/login'} className="outline-btn big"><Camera size={18}/> Start voting</Link></div><div className="hero-meta"><span><strong>{days}</strong> days to close</span><span><strong>6</strong> categories</span><span><strong>1</strong> community</span></div></div><div className="hero-stage"><div className="orb orb1"/><div className="orb orb2"/><div className="photo-card card-a"><img src="/photos/campus.svg"/><div><b>Campus Light</b><small>Campus Life · 128 votes</small></div></div><div className="photo-card card-b"><img src="/photos/nature.svg"/><div><b>After Rain</b><small>Nature · 112 votes</small></div></div><div className="photo-card card-c"><img src="/photos/architecture.svg"/><div><b>Lines & Light</b><small>Architecture · 88 votes</small></div></div><div className="floating-pill"><Trophy size={16}/> Live voting</div></div></section>
 <section className="section"><div className="section-head"><div><span className="eyebrow">THE SHOWCASE</span><h2>Frames worth stopping for.</h2></div><Link to="/gallery" className="text-link">View all <ChevronRight size={16}/></Link></div><div className="masonry">{photos.slice(0,6).map((p,i)=><PhotoTile key={p.id} p={p} featured={i===0}/>)}</div></section>
 <section className="section dark-panel"><div className="split"><div><span className="eyebrow">HOW IT WORKS</span><h2>From shutter to spotlight.</h2><p>Organizers verify eligibility and publish the photographs. Everyone discovers and votes. When voting closes, the platform calculates and publishes the winners.</p></div><div className="steps"><Step n="01" icon={<ShieldCheck/>} title="Curate" text="Organizers verify eligibility and publish the photographs."/><Step n="02" icon={<Filter/>} title="Discover" text="Browse the official gallery by category."/><Step n="03" icon={<Heart/>} title="Vote" text="Cast one vote for each photograph you support."/><Step n="04" icon={<Trophy/>} title="Results" text="When voting closes, winners are calculated and published."/></div></div></section>
 </main>}
function Step({n,icon,title,text}){return <div className="step"><span>{n}</span><div className="step-icon">{icon}</div><div><b>{title}</b><p>{text}</p></div></div>}
function PhotoTile({p,featured}){return <Link to={`/photo/${p.id}`} className={featured?'photo-tile featured':'photo-tile'}><img src={p.image_url}/><div className="tile-overlay"><span>{p.category_name}</span><b>{p.title}</b><small>{p.student_name} · {p.vote_count} votes</small></div></Link>}

function Gallery(){const {categories}=useData();const [photos,setPhotos]=useState(demoPhotos),[cat,setCat]=useState('all'),[q,setQ]=useState('');useEffect(()=>{api('/photos').then(x=>x.length&&setPhotos(x)).catch(()=>{})},[]);const shown=useMemo(()=>photos.filter(p=>(cat==='all'||String(p.category_id)===cat||p.category_name===cat)&&(!q||`${p.title} ${p.student_name} ${p.category_name}`.toLowerCase().includes(q.toLowerCase()))),[photos,cat,q]);return <main className="page"><div className="page-title"><div><span className="eyebrow">THE GALLERY</span><h1>Explore the competition.</h1><p>Find a frame, read the story, and cast your vote.</p></div><div className="search"><Search size={18}/><input placeholder="Search photos or creators" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="chips"><button className={cat==='all'?'chip active':'chip'} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button key={c.id} className={cat===String(c.id)?'chip active':'chip'} onClick={()=>setCat(String(c.id))}>{c.name}</button>)}</div><div className="gallery-grid">{shown.map(p=><PhotoTile key={p.id} p={p}/>)}{!shown.length&&<div className="empty">No frames match your search.</div>}</div></main>}

function PhotoDetail({id}){
 const [p,setP]=useState(null),[voted,setVoted]=useState(false),[competition,setCompetition]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const [ps,c]=await Promise.all([api('/photos'),api('/competition')]);const found=ps.find(x=>String(x.id)===String(id));setP(found||demoPhotos.find(x=>String(x.id)===String(id)));setCompetition(c);if(getUser()?.role==='student'){const votes=await api('/my-votes');setVoted(votes.includes(Number(id)));}}catch{setP(demoPhotos.find(x=>String(x.id)===String(id)))}})()},[id]);
 const votingOpen=competition?.status==='live';
 const vote=async()=>{if(!getUser())return alert('Please sign in as a student to vote.');if(!votingOpen)return alert('Voting is currently closed.');if(voted)return;setBusy(true);try{const r=await api(`/photos/${id}/vote`,{method:'POST'});setP(x=>({...x,vote_count:r.vote_count}));setVoted(true)}catch(e){alert(e.message)}finally{setBusy(false)}};
 if(!p)return <main className="page"><div className="empty">Loading frame…</div></main>;
 return <main className="detail"><Link to="/gallery" className="back">← Back to gallery</Link><div className="detail-grid"><div className="detail-image"><img src={p.image_url}/></div><div className="detail-copy"><span className="eyebrow">{p.category_name}</span><h1>{p.title}</h1><p className="by">Captured by <b>{p.student_name}</b></p><p>{p.description||'An official photograph published by the IEM Photography Competition organizers.'}</p><div className="vote-box"><div><small>COMMUNITY VOTES</small><strong>{p.vote_count}</strong></div><button className="solid-btn big" onClick={vote} disabled={voted||busy||!votingOpen}>{voted?<><CheckCircle2 size={18}/> Voted</>:!votingOpen?<><Clock3 size={18}/> Voting closed</>:<><Heart size={18}/> Vote for this frame</>}</button></div><small className="vote-note">You may vote once for each photograph. Duplicate votes are blocked automatically.</small></div></div></main>
}

function Auth({organizer=false}){const nav=useNavigate();const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[college,setCollege]=useState('IEM/UEM'),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');try{const data=await api(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(register?{name,email,password,college}:{email,password,portal:organizer?'organizer':'student'})});setSession(data.token,data.user);nav(organizer?'/organizer':'/gallery')}catch(e){setError(e.message)}};return <main className="auth-page"><div className="auth-card"><img src="/iem-logo.jpg" className="auth-logo"/><span className="eyebrow">{organizer?'ORGANIZER CONSOLE':'STUDENT PORTAL'}</span><h1>{organizer?'Control the competition.':'Your next frame starts here.'}</h1><p>{organizer?'Manage categories, entries, voting and results from one secure space.':'Sign in to explore the gallery and vote for your favourite frames.'}</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit}>{register&&!organizer&&<><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>College / University<input value={college} onChange={e=>setCollege(e.target.value)} required/></label></>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="solid-btn big full">{register?'Create student account':organizer?'Open organizer console':'Sign in'}</button></form>{!organizer&&<button className="switch" onClick={()=>setRegister(!register)}>{register?'Already have an account? Sign in':'New here? Create a student account'}</button>}<div className="demo">Demo: {organizer?'organizer@iem.local':'student@iem.local'} / ChangeMe123!</div></div></main>}

function Guard({role,children}){const u=getUser();if(!u)return <Navigate to={role==='organizer'?'/organizer/login':'/login'} replace/>;if(u.role!==role)return <Navigate to="/" replace/>;return children}

function StudentEntries(){const [mine,setMine]=useState([]);useEffect(()=>{api('/photos/mine').then(setMine).catch(()=>{})},[]);return <main className="page"><div className="page-title"><div><span className="eyebrow">YOUR PROFILE</span><h1>Published for you.</h1><p>Photographs associated with your account by the competition organizers.</p></div><div className="profile-badge"><Users size={16}/>{getUser()?.name}</div></div><div className="gallery-grid">{mine.length?mine.map(p=><PhotoTile key={p.id} p={p}/>):<div className="empty"><Upload size={28}/><b>No photographs published yet</b><span>When the organizers publish an eligible photograph for you, it will appear here.</span></div>}</div></main>}

function Organizer(){const [tab,setTab]=useState('dashboard'),[stats,setStats]=useState(null),[photos,setPhotos]=useState([]),[students,setStudents]=useState([]),[cats,setCats]=useState([]),[comp,setComp]=useState(null),[results,setResults]=useState(null),[notice,setNotice]=useState('');const load=async()=>{const [s,p,st,c,r,competition]=await Promise.all([api('/organizer/stats'),api('/organizer/photos'),api('/organizer/students'),api('/categories'),api('/organizer/results'),api('/competition')]);setStats(s);setPhotos(p);setStudents(st);setCats(c);setResults(r);setComp(competition)};useEffect(()=>{load().catch(e=>setNotice(e.message))},[]);const close=async()=>{try{const next=comp.status==='draft'?'live':comp.status==='closed'?'live':'closed';await api(`/organizer/competition/${comp.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});await load()}catch(e){setNotice(e.message)}};return <main className="admin"><aside className="admin-side"><div className="admin-brand"><img src="/iem-logo.jpg"/><div><b>IEM PHOTO</b><small>Organizer Console</small></div></div>{[['dashboard',<LayoutDashboard/>,'Dashboard'],['submissions',<ImageIcon/>,'Submissions'],['categories',<Tag/>,'Categories'],['results',<Trophy/>,'Results']].map(([k,i,l])=><button key={k} className={tab===k?'side-active':''} onClick={()=>setTab(k)}>{i}{l}</button>)}<div className="side-bottom"><button onClick={()=>{logout();location.href='/'}}><LogOut/>Sign out</button></div></aside><section className="admin-main"><div className="admin-top"><div><span className="eyebrow">ORGANIZER CONSOLE</span><h1>{comp?.title||'Competition'}</h1></div><div className="status-pill"><span/> {comp?.status||'loading'}</div></div>{notice&&<div className="error">{notice}</div>}{tab==='dashboard'&&<Dashboard stats={stats} comp={comp} onClose={close}/>} {tab==='submissions'&&<Submissions photos={photos} students={students} cats={cats} comp={comp} reload={load}/>} {tab==='categories'&&<Categories cats={cats} reload={load}/>} {tab==='results'&&<AdminResults results={results} photos={photos} comp={comp}/>}</section></main>}
function Dashboard({stats,comp,onClose}){return <div className="admin-content"><div className="stat-grid">{[['Entries',stats?.photos||0,<ImageIcon/>],['Votes',stats?.votes||0,<Heart/>],['Students',stats?.students||0,<Users/>],['Categories',stats?.categories||0,<Tag/>]].map(([l,v,i])=><div className="stat-card" key={l}><div>{i}</div><small>{l}</small><strong>{v}</strong></div>)}</div><div className="admin-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">LIVE CONTROL</span><h2>Competition status</h2></div><button className="outline-btn" onClick={onClose} disabled={!comp}>{comp?.status==='closed'?'Reopen voting':comp?.status==='draft'?'Start voting':'Close voting'}</button></div><div className="timeline"><span className="live-dot"/><div><b>{comp?.status==='closed'?'Voting closed':comp?.status==='draft'?'Competition not started':'Voting is live'}</b><p>{comp?.theme} · {comp?.description}</p><small>{comp?.ends_at?`Voting end: ${new Date(comp.ends_at).toLocaleString()}`:''}</small></div></div></div><div className="panel"><span className="eyebrow">QUICK NOTES</span><h2>Judge-ready workflow</h2><ul className="clean-list"><li><CheckCircle2/>Keep categories consistent.</li><li><CheckCircle2/>Watch duplicate voting automatically.</li><li><CheckCircle2/>Publish results only after closing.</li></ul></div></div></div>}
function Submissions({photos,students,cats,comp,reload}){const [file,setFile]=useState(null),[title,setTitle]=useState(''),[student,setStudent]=useState(''),[cat,setCat]=useState(''),[description,setDescription]=useState('');const submit=async e=>{e.preventDefault();const fd=new FormData();fd.append('image',file);fd.append('title',title);fd.append('studentId',student);fd.append('categoryId',cat);fd.append('competitionId',comp.id);fd.append('description',description);try{await api('/organizer/photos',{method:'POST',body:fd});setTitle('');setDescription('');setFile(null);await reload();alert('Submission added.')}catch(e){alert(e.message)}};return <div className="admin-content"><div className="panel"><div className="panel-head"><div><span className="eyebrow">CURATION</span><h2>Add a student submission</h2></div></div><form className="entry-form" onSubmit={submit}><label>Photo title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Student<select value={student} onChange={e=>setStudent(e.target.value)} required><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.email}</option>)}</select></label><label>Category<select value={cat} onChange={e=>setCat(e.target.value)} required><option value="">Select category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0])} required/></label><label className="wide">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional story behind the frame"/></label><button className="solid-btn big wide"><Upload size={18}/> Publish submission</button></form></div><div className="panel"><div className="panel-head"><h2>All submissions</h2><span>{photos.length} entries</span></div><div className="table-wrap"><table><thead><tr><th>Frame</th><th>Student</th><th>Category</th><th>Votes</th></tr></thead><tbody>{photos.map(p=><tr key={p.id}><td><div className="table-photo"><img src={p.image_url}/><span>{p.title}</span></div></td><td>{p.student_name}</td><td>{p.category_name}</td><td>{p.vote_count}</td></tr>)}</tbody></table></div></div></div>}
function Categories({cats,reload}){const [name,setName]=useState(''),[description,setDescription]=useState('');const add=async e=>{e.preventDefault();try{await api('/organizer/categories',{method:'POST',body:JSON.stringify({name,description})});setName('');setDescription('');reload()}catch(e){alert(e.message)}};return <div className="admin-content"><div className="panel"><span className="eyebrow">STRUCTURE</span><h2>Create a category</h2><form className="entry-form" onSubmit={add}><label>Category name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="solid-btn big"><Tag size={18}/> Add category</button></form></div><div className="category-admin-grid">{cats.map(c=><div className="category-admin" key={c.id}><span><Tag/></span><b>{c.name}</b><p>{c.description}</p></div>)}</div></div>}
function AdminResults({results,photos,comp}){const data=results||{leaderboard:photos,overallWinners:[],categoryWinners:[]};return <div className="admin-content"><div className="panel"><div className="panel-head"><div><span className="eyebrow">FINAL TALLY</span><h2>{comp?.status==='closed'?'Official results':'Voting monitor'}</h2></div><span>{comp?.status==='closed'?'Results published':'Results unlock when voting closes'}</span></div>{comp?.status!=='closed'?<div className="empty"><Clock3 size={28}/><b>Voting is still open</b><span>Keep monitoring votes here. Final winners are calculated only after the organizer closes voting.</span></div>:<><div className="winner-row admin-winners">{data.overallWinners.slice(0,3).map((p,i)=><div className={i===0?'winner-card winner':'winner-card'} key={p.id}><div className="rank">{i===0?<Trophy/>:`0${i+1}`}</div><img src={p.image_url}/><div><span>{p.category_name}</span><b>{p.title}</b><small>{p.student_name} · {p.vote_count} votes</small></div></div>)}</div><div className="leaderboard">{data.leaderboard.slice(0,20).map((p,i)=><div className="leader" key={p.id}><strong>#{i+1}</strong><img src={p.image_url}/><div><b>{p.title}</b><small>{p.student_name} · {p.category_name}</small></div><span>{p.vote_count} votes</span></div>)}</div></>}</div></div>}

function Leaderboard(){const [data,setData]=useState(null);useEffect(()=>{api('/results').then(setData).catch(()=>setData({available:false}))},[]);if(!data)return <main className="page"><div className="empty">Loading results…</div></main>;if(!data.available)return <main className="page"><div className="page-title"><div><span className="eyebrow">THE RESULTS</span><h1>Results are coming.</h1><p>{data.message||'The organizers will publish the official results after voting closes.'}</p></div></div><div className="empty results-wait"><Clock3 size={34}/><b>Voting is still underway.</b><span>Keep exploring the gallery and cast your vote for the photographs you support.</span><Link to="/gallery" className="solid-btn big">Explore gallery</Link></div></main>;return <main className="page"><div className="page-title"><div><span className="eyebrow">OFFICIAL RESULTS</span><h1>And the winners are.</h1><p>Final results calculated from the completed community vote.</p></div></div><div className="winner-row">{data.overallWinners.slice(0,3).map((p,i)=><div className={i===0?'winner-card winner':'winner-card'} key={p.id}><div className="rank">{i===0?<Trophy/>:`0${i+1}`}</div><img src={p.image_url}/><div><span>{p.category_name}</span><b>{p.title}</b><small>{p.student_name} · {p.vote_count} votes</small></div></div>)}</div><section className="section"><div className="section-head"><div><span className="eyebrow">CATEGORY WINNERS</span><h2>Every category has its moment.</h2></div></div><div className="gallery-grid">{data.categoryWinners.map(p=><PhotoTile key={p.id} p={p}/>)}</div></section><div className="leaderboard public">{data.leaderboard.slice(0,20).map((p,i)=><div className="leader" key={p.id}><strong>#{i+1}</strong><img src={p.image_url}/><div><b>{p.title}</b><small>{p.student_name} · {p.category_name}</small></div><span>{p.vote_count} votes</span></div>)}</div></main>}

export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/photo/:id" element={<PhotoRoute/>}/><Route path="/leaderboard" element={<Leaderboard/>}/><Route path="/login" element={<Auth/>}/><Route path="/organizer/login" element={<Auth organizer/>}/><Route path="/my-submissions" element={<Guard role="student"><StudentEntries/></Guard>}/><Route path="/organizer" element={<Guard role="organizer"><Organizer/></Guard>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Layout>}
function PhotoRoute(){const loc=useLocation();return <PhotoDetail id={loc.pathname.split('/').pop()}/>}
